blank_issues_enabled: false
contact_links:
  - name: Сайт QuickRAMDisk / QuickRAMDisk website
    url: https://quickramdisk.pro
    about: Описание, цены и лицензионное соглашение / Overview, pricing and license agreement
