name: Предложение / Feature request
description: Идея, как сделать QuickRAMDisk лучше / An idea to make QuickRAMDisk better
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу вы решаете? / What problem are you trying to solve?
      description: Опишите ситуацию, в которой не хватает возможности / Describe the situation where something is missing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Как это могло бы работать / How it could work
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Версия QuickRAMDisk / QuickRAMDisk version
      placeholder: "1.0.0"
    validations:
      required: false
